#!/usr/bin/env php
<?php
require_once 'vendor/autoload.php';

try {
    $invocation = new \d0x2f\CloverMerge\Invocation($argv);
    $invocation->execute();
} catch (\Exception $e) {
    echo $e->getMessage() . PHP_EOL;
}
